services:
  code-server:
    image: lscr.io/linuxserver/code-server:4.96.4
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - DEFAULT_WORKSPACE=/workspace/dockerfiles
    volumes:
      - /home/jcorbalan:/workspace
      - /opt/code-server/config:/config
    ports:
      - 8443:8443
    restart: unless-stopped
